### ISSUE TITLE
What is the technology?

### ISSUE THREAD

**Issue by ShadyNagy** [Layla-P/WomenOfDotNet#1]
@Layla-P 
When I saw your great source code I thought it is created by [gatsbyjs](https://www.gatsbyjs.com/) but I do not think so.
I wonder what is the technology?

**Comment by Layla-P** [comment]
This is HUGO! gohugo.io it's a static site generator for GOLANG :-)

**Comment by ShadyNagy** [comment]
@Layla-P Good to know, thanks!
